@startuml
!pragma layout smetana
'skinparam defaultFontSize 29

'https://plantuml.com/sequence-diagram
box "(community)" #LightYellow
actor Alice_novice as alice
actor Bob as bob
end box

box "(offchain)" #Coral
actor Forum as forum
end box

box "(community)" #LightGray
actor Communities_novice as community
actor Guarantors_expert as guarantor
end box

box "(multisig)" #Peru
actor BitDAOAdmins_expert as bitdaoadmin
end box

box "(token)" #OliveDrab
actor TokenHolders_novice as tokenholders
endbox

box "(offchain)" #Coral
database Snapshot as snapshot
end box

box "(onchain)" #Lavender
collections Proxy as proxy
collections ProxyAdmin as proxyadmin
collections Executor as executor
collections Token as token
collections BondContract as bondcontract
collections RewardsContract as rewardscontract
collections InsuranceContract as insurancecontract
collections GrantsTreasury as grantstreasury
collections BitDAOTreasury as bitdaotreasury
collections BitDAOGovernanceV2 as bitdaogovernance
end box

autonumber "Current:[00]"

== Current ==

alice -> grantstreasury: create grants treasury
alice <-- grantstreasury: treasury address

alice -> forum: create forum proposal
activate forum
community -> forum: get proposals
community <-- forum: list of proposals
community -> forum: put positive/negative feedback
alice <-- forum: get positive/negative feedback
deactivate forum

community -> community: delegate votes

alice -> snapshot: submit proposal
activate snapshot
tokenholders -> snapshot: get proposals
tokenholders <-- snapshot: list of proposals
tokenholders -> snapshot: vote on open proposals
tokenholders <-- snapshot: vote confirmation

'alice -> snapshot: get Alice's proposal result
'alice <-- snapshot: Alice's proposal pass/fail result

bitdaoadmin -> snapshot: get Alice's proposal result
bitdaoadmin <-- snapshot: Alice's proposal pass/fail result
deactivate snapshot

bitdaoadmin -> bitdaotreasury: transfer funds to grants treasury
bitdaotreasury -> grantstreasury: funds transfer

alt#Gold #DarkSeaGreen trace
  alice <-- grantstreasury: transfer confirmation
end

alice --> alice: execute proposal

newpage

autonumber "Bond:[00]"

== Bond ==


alice -> grantstreasury: create grants treasury
alice <-- grantstreasury: treasury address

' bond

alice -> forum: create forum proposal
activate forum
guarantor -> forum: get proposals
guarantor <-- forum: list of proposals
guarantor -> forum: put positive/negative feedback

alice -> bondcontract: create bond
guarantor -> bondcontract: contribute BIT tokens
guarantor <-- bondcontract: ERC20 Fungible bond tokens (1:1 swap)

' treasury

community -> forum: get proposals
community <-- forum: list of proposals
community -> forum: put positive/negative feedback
alice <-- forum: get positive/negative feedback
deactivate forum

community --> community: delegate votes

alice -> snapshot: submit proposal
activate snapshot
tokenholders -> snapshot: get proposals
tokenholders <-- snapshot: list of proposals
tokenholders -> snapshot: vote on open proposals
tokenholders <-- snapshot: vote confirmation
deactivate snapshot

bitdaoadmin -> bitdaotreasury: allow funds transfer
bitdaotreasury -> grantstreasury: transfer funds

' execution

alice --> alice: execute proposal


' tranche request

'alice -> forum: create tranche release request forum proposal
'activate forum
'guarantor -> forum: get proposals
'guarantor <-- forum: list of proposals
'guarantor -> forum: put positive/negative feedback
'
'community -> forum: get proposals
'community <-- forum: list of proposals
'community -> forum: put positive/negative feedback
'
'alice <-- forum: get positive/negative feedback
'deactivate forum
'
'community --> community: delegate votes

' bond release

alice -> forum: create bond release request forum proposal
activate forum

guarantor -> forum: get proposals
guarantor <-- forum: list of proposals
guarantor -> forum: put positive/negative feedback

community -> forum: get proposals
community <-- forum: list of proposals
community -> forum: put positive/negative feedback

alice <-- forum: get positive/negative feedback
deactivate forum

community --> community: delegate votes

alice -> snapshot: submit bond release request proposal
activate snapshot
guarantor -> snapshot: get proposals
guarantor <-- snapshot: list of proposals
guarantor -> snapshot: vote to release or proportional slash

tokenholders -> snapshot: get proposals
tokenholders <-- snapshot: list of proposals
tokenholders -> snapshot: vote on open proposals
tokenholders <-- snapshot: vote confirmation
deactivate snapshot

bitdaoadmin -> snapshot: get vote result
bitdaoadmin <-- snapshot: pass/fail proposal result

alt#Gold #LightBlue pass
    bitdaoadmin -> bondcontract: release bond
    bitdaoadmin <-- bondcontract: release confirmation
    guarantor -> bondcontract: submit and redeem bond tokens
    guarantor <-- bondcontract: transfer BIT tokens
else #Pink fail
    bitdaoadmin -> bondcontract: slash bond
    bondcontract -> bitdaotreasury: transfer any slashed BIT tokens
    guarantor -> bondcontract: submit and redeem bond tokens (relative to non-slashed portion)
    guarantor <-- bondcontract: transfer BIT tokens
end

alt#Gold #DarkSeaGreen trace
  bitdaoadmin <-- bondcontract: TxHash
end

newpage

autonumber "Roles:[00]"

== Roles ==

alice -> forum: submit create role proposal
community -> forum: list role proposals
community <-- forum: role proposals
community -> forum: positive/negative feedback
alice <-- forum: get positive/negative feedback

community -> community: delegate votes

alice -> snapshot: create admin role

bitdaoadmin -> snapshot: list role proposals
bitdaoadmin <-- snapshot: role proposals
bitdaoadmin -> snapshot: get results
bitdaoadmin <-- snapshot: list of results

bitdaoadmin -> bitdaogovernance: create role

alt#Gold #DarkSeaGreen trace
  bitdaoadmin <-- bitdaogovernance: TxHash
end

newpage

autonumber "Insurance:[00]"

== Insurance ==

alice -> insurancecontract: create insurance ticket


alice -> insurancecontract: pay for insurance daily / monthly


alice -> insurancecontract: compensate

community -> community: delegate votes

alice -> snapshot: submit proposal
guarantor -> snapshot: get proposals
guarantor <-- snapshot: list of proposals
guarantor -> snapshot: vote on proposal
guarantor <-- snapshot: vote confirmation

bitdaoadmin -> snapshot: get vote result
bitdaoadmin <-- snapshot: pass/fail vote result

bitdaoadmin -> bitdaotreasury: allow funds transfer
bitdaotreasury -> insurancecontract: transfer funds

alice <-- insurancecontract: execute proposal


bitdaoadmin -> insurancecontract: if (high debt) terminate alice insurance

community -> community: delegate votes

bitdaoadmin -> snapshot: submit proposal
guarantor -> snapshot: get all proposals
guarantor <-- snapshot: list of proposals
guarantor -> snapshot: vote on proposal

bitdaoadmin -> snapshot: get vote result
bitdaoadmin <-- snapshot: pass/fail vote result

bitdaoadmin -> insurancecontract: terminate insurance
bitdaoadmin <-- insurancecontract: execute proposal

newpage

autonumber "UpgradeGovernance:[00]"

== Upgrade Governance ==

bitdaoadmin -> executor: deploy timelock executor
bitdaoadmin -> bitdaogovernance: deploy initial governance contract logic
bitdaoadmin -> proxyadmin: deploy admin for governance proxy
bitdaoadmin -> proxy: deploy governance proxy and set logic and admin
bitdaoadmin -> proxyadmin: set executor as admin


alice -> bitdaogovernance: deploy new bitdaogovernance implementation

alice -> forum: create forum upgrade proposal with new bitdaogovernance
alice <- community: positive/negative feedback

community -> community: delegate role (developer/all) based votes

alice -> bitdaogovernance: submit upgrade proposal
community -> bitdaogovernance: roles voting

bitdaoadmin -> bitdaogovernance: get roles voting result
bitdaoadmin <-- bitdaogovernance: pass/fail vote result

bitdaoadmin -> bitdaogovernance: start execution
executor <-- bitdaogovernance: execute proposal
executor -> proxyadmin: call governance proxy upgrade to new bitdaogovernance implementation

newpage

autonumber "UpgradeTreasury:[00]"

== Upgrade Treasury ==

bitdaoadmin -> bitdaotreasury: deploy initial treasury contract logic, set governance
bitdaoadmin -> proxyadmin: deploy admin for treasury proxy
bitdaoadmin -> proxy: deploy treasury proxy and set logic and admin
bitdaoadmin -> proxyadmin: set governance executor as admin


alice -> bitdaotreasury: deploy new bitdaotreasury implementation

alice -> forum: create forum upgrade proposal with new bitdaogovernance
alice <- community: positive/negative feedback

community -> community: delegate role (treasury/developer/all) based votes

alice -> bitdaogovernance: submit upgrade proposal
community -> bitdaogovernance: roles voting

bitdaoadmin -> bitdaogovernance: get roles voting result
bitdaoadmin <-- bitdaogovernance: pass/fail vote result

bitdaoadmin -> bitdaogovernance: start execution
executor <-- bitdaogovernance: execute proposal
executor -> proxyadmin: call treasury proxy upgrade to new bitdaotreasury implementation

newpage

autonumber "UpgradeVault:[00]"

== Upgrade Vault ==

bitdaoadmin -> vault: deploy initial vault contract logic, set treasury
bitdaoadmin -> proxyadmin: deploy admin for vault proxy
bitdaoadmin -> proxy: deploy vault proxy and set logic and admin
bitdaoadmin -> proxyadmin: set governance executor as admin


alice -> vault: deploy new vault implementation

alice -> forum: create forum upgrade proposal with new bitdaogovernance
alice <- community: positive/negative feedback

community -> community: delegate role (treasury/all) based votes

alice -> bitdaogovernance: submit upgrade proposal
community -> bitdaogovernance: roles voting

bitdaoadmin -> bitdaogovernance: get roles voting result
bitdaoadmin <-- bitdaogovernance: pass/fail vote result

bitdaoadmin -> bitdaogovernance: start execution
executor <-- bitdaogovernance: execute proposal
executor -> proxyadmin: call vault proxy upgrade to new vault implementation

newpage

autonumber "UpgradeBond:[00]"

== Upgrade Bond ==

bitdaoadmin -> bondcontract: deploy initial bond factory contract logic, set treasury
bitdaoadmin -> proxyadmin: deploy admin for bond factory proxy
bitdaoadmin -> proxy: deploy bond factory proxy and set logic and admin
bitdaoadmin -> proxyadmin: set governance executor as admin


alice -> bondcontract: deploy new bond factory contract implementation

alice -> forum: create forum upgrade proposal with new bitdaogovernance
alice <- community: positive/negative feedback

community -> community: delegate role (treasury/all) based votes

alice -> bitdaogovernance: submit upgrade proposal
community -> bitdaogovernance: roles voting

bitdaoadmin -> bitdaogovernance: get roles voting result
bitdaoadmin <-- bitdaogovernance: pass/fail vote result

bitdaoadmin -> bitdaogovernance: start execution
executor <-- bitdaogovernance: execute proposal
executor -> proxyadmin: call bond contract proxy upgrade to new bond contract implementation

newpage

autonumber "UpgradeToken:[00]"

== Upgrade Token / Derivative ==

bitdaoadmin -> token: deploy initial token/derivative logic
bitdaoadmin -> proxyadmin: deploy admin for token proxy
bitdaoadmin -> proxy: deploy token proxy and set logic and admin
bitdaoadmin -> proxyadmin: set governance executor as admin


alice -> token: deploy new token contract implementation

alice -> forum: create forum upgrade proposal with new bitdaogovernance
alice <- community: positive/negative feedback

community -> community: delegate role based votes

alice -> bitdaogovernance: submit upgrade proposal
community -> bitdaogovernance: roles voting

bitdaoadmin -> bitdaogovernance: get roles voting result
bitdaoadmin <-- bitdaogovernance: pass/fail vote result

bitdaoadmin -> bitdaogovernance: start execution
executor <-- bitdaogovernance: execute proposal
executor -> proxyadmin: call token proxy upgrade to new token implementation

newpage

autonumber "UpgradeSnapshot:[00]"

== Upgrade Snapshot ==

alice -> forum: create snapshot upgrade request forum proposal
activate forum

guarantor -> forum: get proposals
guarantor <-- forum: list of proposals
guarantor -> forum: put positive/negative feedback

community -> forum: get proposals
community <-- forum: list of proposals
community -> forum: put positive/negative feedback

alice <-- forum: get positive/negative feedback
deactivate forum

community --> community: delegate votes

alice -> snapshot: submit snapshot upgrade request proposal
activate snapshot
guarantor -> snapshot: get proposals
guarantor <-- snapshot: list of proposals
guarantor -> snapshot: vote to release or proportional slash

tokenholders -> snapshot: get proposals
tokenholders <-- snapshot: list of proposals
tokenholders -> snapshot: vote on open proposals
tokenholders <-- snapshot: vote confirmation
deactivate snapshot

bitdaoadmin -> snapshot: get vote result
bitdaoadmin <-- snapshot: pass/fail vote result
bitdaoadmin -> snapshot: upgrade snapshot

newpage

autonumber "UpgradeMultisig:[00]"

== Upgrade Multisig ==

alice -> forum: create multisig upgrade request forum proposal
activate forum

guarantor -> forum: get proposals
guarantor <-- forum: list of proposals
guarantor -> forum: put positive/negative feedback

community -> forum: get proposals
community <-- forum: list of proposals
community -> forum: put positive/negative feedback

alice <-- forum: get positive/negative feedback
deactivate forum

community --> community: delegate votes

alice -> snapshot: submit multisig upgrade request proposal
activate snapshot
guarantor -> snapshot: get proposals
guarantor <-- snapshot: list of proposals
guarantor -> snapshot: vote to release or proportional slash

tokenholders -> snapshot: get proposals
tokenholders <-- snapshot: list of proposals
tokenholders -> snapshot: vote on open proposals
tokenholders <-- snapshot: vote confirmation
deactivate snapshot

bitdaoadmin -> snapshot: get vote result
bitdaoadmin <-- snapshot: pass/fail vote result
bitdaoadmin -> multisig: create a new multisig
bitdaoadmin -> multisig: transfer funds from the old multisig to the new multisig

newpage

autonumber "UpgradeOwners:[00]"

== Upgrade Owners ==

alice -> forum: create owners upgrade request forum proposal
activate forum

guarantor -> forum: get proposals
guarantor <-- forum: list of proposals
guarantor -> forum: put positive/negative feedback

community -> forum: get proposals
community <-- forum: list of proposals
community -> forum: put positive/negative feedback

alice <-- forum: get positive/negative feedback
deactivate forum

community --> community: delegate votes

alice -> snapshot: submit owners upgrade request proposal
activate snapshot
guarantor -> snapshot: get proposals
guarantor <-- snapshot: list of proposals
guarantor -> snapshot: vote to release or proportional slash

tokenholders -> snapshot: get proposals
tokenholders <-- snapshot: list of proposals
tokenholders -> snapshot: vote on open proposals
tokenholders <-- snapshot: vote confirmation
deactivate snapshot

bitdaoadmin -> snapshot: get vote result
bitdaoadmin <-- snapshot: pass/fail vote result
bitdaoadmin -> owner: create a new owner
bitdaoadmin -> contract: transfer ownership to the new owner


newpage

autonumber "Rewards:[00]"

== Rewards ==

alice -> forum: create forum proposal
alice <- guarantor: positive/negative feedback
alice -> rewardscontract: create rewards program

community -> community: delegate votes

alice -> snapshot: submit proposal

bitdaoadmin -> bitdaotreasury: allow funds
bitdaotreasury -> rewardscontract: transfer funds for rewards

alice <-- rewardscontract: execute proposal


bob -> forum: create forum proposal
bob <- guarantor: positive/negative feedback

bob -> snapshot: submit release request
community -> community: delegate votes
community -> snapshot: vote
community -> rewardscontract: claim reward


@enduml